-- Production `public` schema, reconstructed from pg_catalog.
-- GENERATED by scripts/dump-production-schema.py — do not hand-edit.
-- Schema only. No rows: see the script docstring for why.

-- ── roles (cluster-level, but the policies below do not stand up without them) ──
do $$ begin
  create role tenant_app nologin;
exception when duplicate_object then null; end $$;

-- ── extensions ──
create extension if not exists pg_stat_statements with schema extensions;
create extension if not exists pgcrypto with schema extensions;
create extension if not exists supabase_vault with schema vault;
create extension if not exists "uuid-ossp" with schema extensions;

-- ── tables (columns only; constraints follow, so nothing forward-references) ──
create table if not exists public.activity_log (
  id uuid default gen_random_uuid() not null,
  profile_id uuid,
  type text,
  description text,
  created_at timestamp with time zone default now()
);

create table if not exists public.competitors (
  id uuid default gen_random_uuid() not null,
  profile_id uuid,
  google_place_id text not null,
  business_name text not null,
  category text,
  address text,
  rating numeric(2,1),
  review_count integer,
  last_post_at timestamp with time zone,
  last_checked_at timestamp with time zone,
  created_at timestamp with time zone default now(),
  had_recent_activity boolean default false
);

create table if not exists public.found_alerts (
  id uuid default gen_random_uuid() not null,
  profile_id uuid,
  search_term text,
  action text,
  notified boolean default false,
  created_at timestamp with time zone default now()
);

create table if not exists public.optimizations (
  id uuid default uuid_generate_v4() not null,
  profile_id uuid not null,
  type text not null,
  before_data jsonb,
  after_data jsonb,
  applied boolean default false,
  applied_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.posts (
  id uuid default uuid_generate_v4() not null,
  profile_id uuid not null,
  content text not null,
  status text default 'scheduled'::text,
  scheduled_for timestamp with time zone not null,
  posted_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.profile_analysis (
  id uuid default gen_random_uuid() not null,
  profile_id uuid,
  issues jsonb,
  quick_wins jsonb,
  estimated_score_increase integer,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists public.profiles (
  id uuid default gen_random_uuid() not null,
  user_id uuid not null,
  google_account_id text,
  google_location_name text,
  business_name text default ''::text not null,
  category text default ''::text,
  address text default ''::text,
  latitude double precision,
  longitude double precision,
  streak_weeks integer default 0,
  last_auto_post_at timestamp with time zone,
  total_auto_posts integer default 0,
  total_auto_replies integer default 0,
  created_at timestamp with time zone default now(),
  city text,
  audit_score integer,
  audit_score_after integer,
  updated_at timestamp with time zone default now(),
  google_place_id text,
  tenant_id uuid default 'e4802656-afbd-4a8a-8f89-36caf81b41e6'::uuid not null
);

create table if not exists public.referrals (
  id uuid default gen_random_uuid() not null,
  referrer_id uuid not null,
  referred_id uuid,
  referred_name text,
  referral_code text not null,
  status text default 'pending'::text,
  reward_applied boolean default false,
  created_at timestamp with time zone default now(),
  tenant_id uuid default 'e4802656-afbd-4a8a-8f89-36caf81b41e6'::uuid not null
);

create table if not exists public.retailer_invites (
  id uuid default gen_random_uuid() not null,
  retailer_id uuid not null,
  tenant_id uuid not null,
  email text not null,
  token_hash text not null,
  status text default 'pending'::text not null,
  sent_at timestamp with time zone,
  expires_at timestamp with time zone not null,
  accepted_at timestamp with time zone,
  user_id uuid,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.retailers (
  id uuid default gen_random_uuid() not null,
  tenant_id uuid not null,
  source text default 'tarkett-scraper'::text not null,
  source_ref text,
  place_id text,
  name text not null,
  town text,
  nation text,
  rating numeric(2,1),
  review_count integer,
  photo_count integer,
  has_website boolean,
  match_confidence text,
  headline_gap text,
  score integer,
  band text,
  score_source text,
  scored_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  contact_email text,
  user_id uuid
);

create table if not exists public.review_replies (
  id uuid default gen_random_uuid() not null,
  review_id uuid not null,
  reply_content text not null,
  status text default 'pending'::text not null,
  published_at timestamp with time zone,
  created_at timestamp with time zone default now(),
  tenant_id uuid default 'e4802656-afbd-4a8a-8f89-36caf81b41e6'::uuid not null
);

create table if not exists public.reviews (
  id uuid default gen_random_uuid() not null,
  profile_id uuid not null,
  google_review_id text not null,
  reviewer_name text default ''::text,
  rating integer not null,
  comment text default ''::text,
  review_date timestamp with time zone default now(),
  created_at timestamp with time zone default now(),
  reply_content text,
  replied_at timestamp with time zone,
  tenant_id uuid default 'e4802656-afbd-4a8a-8f89-36caf81b41e6'::uuid not null
);

create table if not exists public.scheduled_posts (
  id uuid default gen_random_uuid() not null,
  profile_id uuid not null,
  content text not null,
  scheduled_for timestamp with time zone not null,
  status text default 'pending_approval'::text not null,
  google_post_id text,
  published_at timestamp with time zone,
  created_at timestamp with time zone default now(),
  tenant_id uuid default 'e4802656-afbd-4a8a-8f89-36caf81b41e6'::uuid not null
);

create table if not exists public.score_history (
  id uuid default gen_random_uuid() not null,
  retailer_id uuid not null,
  score integer not null,
  band text,
  score_source text not null,
  scored_at timestamp with time zone not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.sms_log (
  id uuid default gen_random_uuid() not null,
  user_id uuid not null,
  phone_number text not null,
  message_type text not null,
  message_body text not null,
  twilio_sid text,
  status text default 'sent'::text,
  created_at timestamp with time zone default now(),
  tenant_id uuid default 'e4802656-afbd-4a8a-8f89-36caf81b41e6'::uuid not null
);

create table if not exists public.tenants (
  id uuid default gen_random_uuid() not null,
  slug text not null,
  status text default 'active'::text not null,
  hostname text not null,
  hostname_aliases text[] default '{}'::text[] not null,
  app_url text not null,
  brand_name text not null,
  wordmark text not null,
  legal_entity text,
  marketing_url text,
  email_from text,
  support_email text,
  team_email text,
  privacy_email text,
  price_monthly_pence integer,
  proof_location text,
  meta_title text,
  meta_description text,
  palette jsonb not null,
  google_client_id text,
  google_client_secret text,
  google_redirect_uri text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.users (
  id uuid default gen_random_uuid() not null,
  email text,
  name text default ''::text not null,
  phone_number text,
  sms_enabled boolean default true,
  google_refresh_token text,
  token_status text default 'valid'::text,
  token_invalid_at timestamp with time zone,
  subscription_status text default 'none'::text,
  stripe_customer_id text,
  stripe_subscription_id text,
  auto_post_enabled boolean default true,
  auto_reply_enabled boolean default true,
  referral_code text,
  referred_by text,
  pause_until timestamp with time zone,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  subscription_id text,
  onboarding_step text default 'pending'::text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  tenant_id uuid default 'e4802656-afbd-4a8a-8f89-36caf81b41e6'::uuid not null
);

create table if not exists public.weekly_stats (
  id uuid default gen_random_uuid() not null,
  profile_id uuid not null,
  week_start date not null,
  views integer default 0,
  calls integer default 0,
  direction_requests integer default 0,
  website_clicks integer default 0,
  created_at timestamp with time zone default now(),
  tenant_id uuid default 'e4802656-afbd-4a8a-8f89-36caf81b41e6'::uuid not null
);

-- ── primary keys ──
do $$ begin
  alter table public.activity_log add constraint activity_log_pkey PRIMARY KEY (id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.competitors add constraint competitors_pkey PRIMARY KEY (id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.found_alerts add constraint found_alerts_pkey PRIMARY KEY (id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.optimizations add constraint optimizations_pkey PRIMARY KEY (id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.posts add constraint posts_pkey PRIMARY KEY (id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.profile_analysis add constraint profile_analysis_pkey PRIMARY KEY (id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.profiles add constraint profiles_pkey PRIMARY KEY (id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.referrals add constraint referrals_pkey PRIMARY KEY (id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.retailer_invites add constraint retailer_invites_pkey PRIMARY KEY (id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.retailers add constraint retailers_pkey PRIMARY KEY (id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.review_replies add constraint review_replies_pkey PRIMARY KEY (id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.reviews add constraint reviews_pkey PRIMARY KEY (id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.scheduled_posts add constraint scheduled_posts_pkey PRIMARY KEY (id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.score_history add constraint score_history_pkey PRIMARY KEY (id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.sms_log add constraint sms_log_pkey PRIMARY KEY (id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.tenants add constraint tenants_pkey PRIMARY KEY (id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.users add constraint users_pkey PRIMARY KEY (id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.weekly_stats add constraint weekly_stats_pkey PRIMARY KEY (id);
exception when duplicate_table or duplicate_object then null; end $$;

-- ── unique constraints ──
do $$ begin
  alter table public.competitors add constraint competitors_profile_id_google_place_id_key UNIQUE (profile_id, google_place_id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.profile_analysis add constraint profile_analysis_profile_id_key UNIQUE (profile_id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.tenants add constraint tenants_hostname_key UNIQUE (hostname);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.tenants add constraint tenants_slug_key UNIQUE (slug);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.users add constraint users_referral_code_key UNIQUE (referral_code);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.weekly_stats add constraint weekly_stats_profile_id_week_start_key UNIQUE (profile_id, week_start);
exception when duplicate_table or duplicate_object then null; end $$;

-- ── check constraints ──
do $$ begin
  alter table public.optimizations add constraint optimizations_type_check CHECK ((type = ANY (ARRAY['description'::text, 'services'::text, 'qa'::text, 'full'::text])));
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.posts add constraint posts_status_check CHECK ((status = ANY (ARRAY['scheduled'::text, 'posted'::text, 'failed'::text])));
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.retailer_invites add constraint retailer_invites_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'accepted'::text, 'revoked'::text])));
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.retailers add constraint retailers_match_confidence_check CHECK ((match_confidence = ANY (ARRAY['high'::text, 'review'::text, 'not_found'::text])));
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.retailers add constraint retailers_score_source_check CHECK ((score_source = ANY (ARRAY['batch'::text, 'live'::text])));
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.score_history add constraint score_history_score_source_check CHECK ((score_source = ANY (ARRAY['batch'::text, 'live'::text])));
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.tenants add constraint google_client_secret_encrypted CHECK (((google_client_secret IS NULL) OR (google_client_secret ~~ 'v1.%'::text)));
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.users add constraint google_refresh_token_encrypted CHECK (((google_refresh_token IS NULL) OR (google_refresh_token ~~ 'v1.%'::text)));
exception when duplicate_table or duplicate_object then null; end $$;

-- ── foreign keys ──
do $$ begin
  alter table public.profiles add constraint profiles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.profiles add constraint profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.referrals add constraint referrals_referred_id_fkey FOREIGN KEY (referred_id) REFERENCES users(id) ON DELETE SET NULL;
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.referrals add constraint referrals_referrer_id_fkey FOREIGN KEY (referrer_id) REFERENCES users(id) ON DELETE CASCADE;
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.referrals add constraint referrals_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.retailer_invites add constraint retailer_invites_retailer_id_fkey FOREIGN KEY (retailer_id) REFERENCES retailers(id) ON DELETE CASCADE;
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.retailer_invites add constraint retailer_invites_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.retailer_invites add constraint retailer_invites_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL;
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.retailers add constraint retailers_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.retailers add constraint retailers_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL;
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.review_replies add constraint review_replies_review_id_fkey FOREIGN KEY (review_id) REFERENCES reviews(id) ON DELETE CASCADE;
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.review_replies add constraint review_replies_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.reviews add constraint reviews_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.reviews add constraint reviews_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.scheduled_posts add constraint scheduled_posts_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.scheduled_posts add constraint scheduled_posts_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.score_history add constraint score_history_retailer_id_fkey FOREIGN KEY (retailer_id) REFERENCES retailers(id) ON DELETE CASCADE;
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.sms_log add constraint sms_log_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.sms_log add constraint sms_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.users add constraint users_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.weekly_stats add constraint weekly_stats_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.weekly_stats add constraint weekly_stats_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
exception when duplicate_table or duplicate_object then null; end $$;

-- ── indexes (constraint-backed ones excluded — they arrive above) ──
create index if not exists idx_activity_profile ON public.activity_log USING btree (profile_id);
create index if not exists idx_competitors_profile ON public.competitors USING btree (profile_id);
create index if not exists idx_found_alerts_profile ON public.found_alerts USING btree (profile_id);
create index if not exists idx_posts_profile_id ON public.posts USING btree (profile_id);
create index if not exists idx_posts_status ON public.posts USING btree (status);
create index if not exists idx_profiles_user_id ON public.profiles USING btree (user_id);
create index if not exists profiles_tenant_id_idx ON public.profiles USING btree (tenant_id);
create index if not exists idx_referrals_code ON public.referrals USING btree (referral_code);
create index if not exists idx_referrals_referrer_id ON public.referrals USING btree (referrer_id);
create index if not exists referrals_tenant_id_idx ON public.referrals USING btree (tenant_id);
create unique index if not exists retailer_invites_one_pending_idx ON public.retailer_invites USING btree (retailer_id) WHERE (status = 'pending'::text);
create index if not exists retailer_invites_pending_expiry_idx ON public.retailer_invites USING btree (expires_at) WHERE (status = 'pending'::text);
create index if not exists retailer_invites_retailer_idx ON public.retailer_invites USING btree (retailer_id);
create index if not exists retailer_invites_tenant_idx ON public.retailer_invites USING btree (tenant_id);
create unique index if not exists retailer_invites_token_hash_idx ON public.retailer_invites USING btree (token_hash);
create index if not exists retailers_place_id_idx ON public.retailers USING btree (place_id);
create unique index if not exists retailers_source_ref_idx ON public.retailers USING btree (source, source_ref);
create index if not exists retailers_tenant_id_idx ON public.retailers USING btree (tenant_id);
create unique index if not exists retailers_user_id_idx ON public.retailers USING btree (user_id) WHERE (user_id IS NOT NULL);
create index if not exists idx_review_replies_review_id ON public.review_replies USING btree (review_id);
create index if not exists idx_review_replies_status ON public.review_replies USING btree (status);
create index if not exists review_replies_tenant_id_idx ON public.review_replies USING btree (tenant_id);
create index if not exists idx_reviews_google_id ON public.reviews USING btree (google_review_id);
create index if not exists idx_reviews_google_review_id ON public.reviews USING btree (google_review_id);
create index if not exists idx_reviews_profile_id ON public.reviews USING btree (profile_id);
create unique index if not exists reviews_tenant_greview_id_key ON public.reviews USING btree (tenant_id, google_review_id);
create index if not exists reviews_tenant_id_idx ON public.reviews USING btree (tenant_id);
create index if not exists idx_scheduled_posts_profile_id ON public.scheduled_posts USING btree (profile_id);
create index if not exists idx_scheduled_posts_scheduled_for ON public.scheduled_posts USING btree (scheduled_for);
create index if not exists idx_scheduled_posts_status ON public.scheduled_posts USING btree (status);
create index if not exists scheduled_posts_tenant_id_idx ON public.scheduled_posts USING btree (tenant_id);
create unique index if not exists score_history_event_idx ON public.score_history USING btree (retailer_id, score_source, scored_at);
create index if not exists score_history_retailer_idx ON public.score_history USING btree (retailer_id, scored_at DESC);
create index if not exists idx_sms_log_user_type_created ON public.sms_log USING btree (user_id, message_type, created_at);
create index if not exists sms_log_tenant_id_idx ON public.sms_log USING btree (tenant_id);
create index if not exists idx_users_referral_code ON public.users USING btree (referral_code);
create index if not exists idx_users_subscription_status ON public.users USING btree (subscription_status);
create index if not exists idx_users_token_status ON public.users USING btree (token_status);
create unique index if not exists users_tenant_email_key ON public.users USING btree (tenant_id, email);
create index if not exists users_tenant_id_idx ON public.users USING btree (tenant_id);
create unique index if not exists users_tenant_referral_code_key ON public.users USING btree (tenant_id, referral_code);
create index if not exists idx_weekly_stats_profile_week ON public.weekly_stats USING btree (profile_id, week_start);
create index if not exists weekly_stats_tenant_id_idx ON public.weekly_stats USING btree (tenant_id);

-- ── functions (after tables: they reference them; before policies: policies call them) ──
CREATE OR REPLACE FUNCTION public.current_tenant_id()
 RETURNS uuid
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public', 'pg_catalog'
AS $function$
declare v text;
begin
  v := nullif(current_setting('app.tenant_id', true), '');
  if v is null then
    v := nullif(nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'tenant_id', '');
  end if;
  if v is null then
    raise exception 'no tenant context set (app.tenant_id / jwt tenant_id claim)'
      using errcode = '42501';
  end if;
  return v::uuid;
end
$function$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public.users (id, email, name, referral_code)
  VALUES (
    NEW.id, 
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'name', ''),
    UPPER(SUBSTRING(NEW.id::text, 1, 8))
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$function$;

-- ── triggers owned by this app, including ones outside public ──
do $$ begin
  CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();
exception when duplicate_object then null; end $$;

-- ── row level security ──
alter table public.activity_log enable row level security;
alter table public.competitors enable row level security;
alter table public.found_alerts enable row level security;
alter table public.optimizations enable row level security;
alter table public.posts enable row level security;
alter table public.profile_analysis enable row level security;
alter table public.profiles enable row level security;
alter table public.referrals enable row level security;
alter table public.review_replies enable row level security;
alter table public.reviews enable row level security;
alter table public.scheduled_posts enable row level security;
alter table public.sms_log enable row level security;
alter table public.tenants enable row level security;
alter table public.users enable row level security;
alter table public.weekly_stats enable row level security;

-- ── policies ──
do $$ begin
create policy "Users read own profiles" on public.profiles
  as permissive
  for select
  to public
  using ((user_id = auth.uid()));
exception when duplicate_object then null; end $$;
do $$ begin
create policy tenant_isolation on public.referrals
  as permissive
  for all
  to tenant_app
  using ((tenant_id = current_tenant_id()))
  with check ((tenant_id = current_tenant_id()));
exception when duplicate_object then null; end $$;
do $$ begin
create policy tenant_isolation on public.review_replies
  as permissive
  for all
  to tenant_app
  using ((tenant_id = current_tenant_id()))
  with check ((tenant_id = current_tenant_id()));
exception when duplicate_object then null; end $$;
do $$ begin
create policy "Users read own reviews" on public.reviews
  as permissive
  for select
  to public
  using ((profile_id IN ( SELECT profiles.id
   FROM profiles
  WHERE (profiles.user_id = auth.uid()))));
exception when duplicate_object then null; end $$;
do $$ begin
create policy "Users read own posts" on public.scheduled_posts
  as permissive
  for select
  to public
  using ((profile_id IN ( SELECT profiles.id
   FROM profiles
  WHERE (profiles.user_id = auth.uid()))));
exception when duplicate_object then null; end $$;
do $$ begin
create policy tenant_isolation on public.sms_log
  as permissive
  for all
  to tenant_app
  using ((tenant_id = current_tenant_id()))
  with check ((tenant_id = current_tenant_id()));
exception when duplicate_object then null; end $$;
do $$ begin
create policy tenant_self_read on public.tenants
  as permissive
  for select
  to tenant_app
  using ((id = current_tenant_id()));
exception when duplicate_object then null; end $$;
do $$ begin
create policy "Users read own" on public.users
  as permissive
  for select
  to public
  using ((id = auth.uid()));
exception when duplicate_object then null; end $$;
do $$ begin
create policy "Users update own" on public.users
  as permissive
  for update
  to public
  using ((id = auth.uid()));
exception when duplicate_object then null; end $$;
do $$ begin
create policy tenant_isolation on public.weekly_stats
  as permissive
  for all
  to tenant_app
  using ((tenant_id = current_tenant_id()))
  with check ((tenant_id = current_tenant_id()));
exception when duplicate_object then null; end $$;

